#!/usr/bin/env bash

set -euxo pipefail

help_info() {
  echo "
Usage: ${0##*/} [options]
Build Linux packages for Gram.

At least one of --tarball, --deb, or --rpm must be specified.

Options:
  -h, --help     Display this help and exit.
  --no-build     Skip building binaries (assume they're already built).
  --flatpak      Set GRAM_BUNDLE_TYPE=flatpak so that this can be included in system info.
  --tarball      Build a release .tar.gz archive.
  --deb          Build a .deb package.
  --rpm          Build a .rpm package.
  "
}

DO_BUILD=true
DO_TARBALL=false
DO_DEB=false
DO_RPM=false

while [[ $# -gt 0 ]]; do
    case $1 in
        -h|--help)
            help_info
            exit 0
            ;;
        --flatpak)
            export GRAM_BUNDLE_TYPE=flatpak
            shift
            ;;
        --no-build)
            DO_BUILD=false
            shift
            ;;
        --tarball)
            DO_TARBALL=true
            shift
            ;;
        --deb)
            DO_DEB=true
            shift
            ;;
        --rpm)
            DO_RPM=true
            shift
            ;;
        --)
            shift
            break
            ;;
        -*)
            echo "Unknown option: $1" >&2
            help_info
            exit 1
            ;;
        *)
            echo "Error: Unexpected argument: $1" >&2
            help_info
            exit 1
            ;;
    esac
done

# Throw error if no arguments given
if [[ "$DO_TARBALL" == "false" && "$DO_DEB" == "false" && "$DO_RPM" == "false" ]]; then
    echo "Error: At least one of --tarball, --deb, or --rpm must be specified." >&2
    help_info
    exit 1
fi

export GRAM_BUNDLE=true

arch=$(uname -m)

# work around incompatibility with newer GCC:
# https://github.com/zed-industries/zed/issues/24880
currentversion="$(gcc -dumpversion)"
requiredversion="14"
version_info=$(rustc --version --verbose)
host_line=$(echo "$version_info" | grep host)
target_triple=${host_line#*: }
if [ "$(printf '%s\n' "$requiredversion" "$currentversion" | sort -V | head -n1)" = "$requiredversion" ]; then
    echo "Handle GCC version 14+ when compiling remote server..."
    export AWS_LC_SYS_CC=clang
    export REMOTE_SERVER_TARGET=$target_triple
fi

if [[ "$DO_DEB" == "true" || "$DO_RPM" == "true" ]]; then
    export REMOTE_SERVER_TARGET=$target_triple
fi

channel=$(<crates/gram/RELEASE_CHANNEL)
target_dir="${CARGO_TARGET_DIR:-target}"

version="$(script/get-crate-version gram)"
export RELEASE_VERSION="${version}"

musl_triple=${target_triple%-gnu}-musl
remote_server_triple=${REMOTE_SERVER_TARGET:-"${musl_triple}"}

if command -v rustup >/dev/null 2>&1; then
    rustup target add "$remote_server_triple"
fi

# Generate the licenses first, so they can be baked into the binaries
script/generate-licenses

export CC=$(which clang)

if [ "$DO_BUILD" = "true" ]; then
    export RUSTFLAGS="${RUSTFLAGS:-} -C link-args=-Wl,--disable-new-dtags,-rpath,\$ORIGIN/../lib"
    cargo build --release --target "${target_triple}" --package gram --package cli
    # Build remote_server separately to prevent feature unification from other crates
    # from influencing dynamic libraries required by it.
    if [[ "$remote_server_triple" == "$musl_triple" ]]; then
        export RUSTFLAGS="${RUSTFLAGS:-} -C target-feature=+crt-static"
    fi
    cargo build --release --target "${remote_server_triple}" --package remote_server
fi

# Ensure that remote_server does not depend on libssl nor libcrypto
if ldd "${target_dir}/${remote_server_triple}/release/remote_server" | grep -q 'libcrypto\|libssl'; then
    if [[ "$remote_server_triple" == *-musl ]]; then
        echo "Error: remote_server still depends on libssl or libcrypto" && exit 1
    else
        echo "Info: Using non-musl remote-server build."
    fi
fi

export DO_STARTUP_NOTIFY="true"
export APP_CLI="gram"
export APP_ICON="gram"
export APP_ARGS="%U"
if [[ "$channel" == "dev" ]]; then
    export APP_NAME="Gram Dev"
else
    export APP_NAME="Gram"
fi

suffix=""
if [ "$channel" != "stable" ]; then
    suffix="-$channel"
fi

# Strip debug symbols (keeps symbol table for backtraces)
objcopy --strip-debug "${target_dir}/${target_triple}/release/gram"
objcopy --strip-debug "${target_dir}/${target_triple}/release/cli"
objcopy --strip-debug "${target_dir}/${remote_server_triple}/release/remote_server"

# Bundle tarball
if [ "$DO_TARBALL" = "true" ]; then
    temp_dir=$(mktemp -d)
    gram_dir="${temp_dir}/gram${suffix}.app"

    mkdir -p "${gram_dir}/bin" "${gram_dir}/libexec"
    cp "${target_dir}/${target_triple}/release/gram" "${gram_dir}/libexec/gram-editor"
    cp "${target_dir}/${target_triple}/release/cli" "${gram_dir}/bin/gram"

    mkdir -p "${gram_dir}/lib"
    ldd "${target_dir}/${target_triple}/release/gram" \
        | cut -d' ' -f3 \
        | grep -v '\<\(libstdc++.so\|libc.so\|libgcc_s.so\|libm.so\|libpthread.so\|libdl.so\)' \
        | xargs -I{} cp {} "${gram_dir}/lib/"

    mkdir -p "${gram_dir}/share/icons/hicolor/512x512/apps"
    cp "crates/gram/resources/app-icon${suffix}.png" "${gram_dir}/share/icons/hicolor/512x512/apps/gram.png"
    mkdir -p "${gram_dir}/share/icons/hicolor/1024x1024/apps"
    cp "crates/gram/resources/app-icon${suffix}@2x.png" "${gram_dir}/share/icons/hicolor/1024x1024/apps/gram.png"

    mkdir -p "${gram_dir}/share/applications"
    envsubst < "crates/gram/resources/gram.desktop.in" > "${gram_dir}/share/applications/gram${suffix}.desktop"
    chmod +x "${gram_dir}/share/applications/gram${suffix}.desktop"

    cp "assets/licenses.md" "${gram_dir}/licenses.md"

    archive="gram-linux-${arch}.tar.gz"
    remove_match="gram(-[a-zA-Z0-9]+)?-linux-$(uname -m)\.tar\.gz"
    ls "${target_dir}/release" | grep -E "${remove_match}" | xargs -d "\n" -I {} rm -f "${target_dir}/release/{}" || true
    tar -czvf "${target_dir}/release/${archive}" -C "${temp_dir}" "gram${suffix}.app"

    gzip -f --stdout --best "${target_dir}/${remote_server_triple}/release/remote_server" \
        > "${target_dir}/gram-remote-server-linux-${arch}.gz"
fi

# Bundle .deb package
if [ "$DO_DEB" = "true" ]; then
    envsubst < "crates/gram/resources/gram.desktop.in" > "crates/gram/resources/gram.desktop"
    CARGO_TARGET_DIR="${target_dir}/${target_triple}" cargo deb -p gram --no-build --compress-type xz
fi

# Bundle .rpm package
if [ "$DO_RPM" = "true" ]; then
    envsubst < "crates/gram/resources/gram.desktop.in" > "crates/gram/resources/gram.desktop"
    cargo generate-rpm -p crates/gram --target-dir "${target_dir}/${target_triple}" --payload-compress zstd
fi
