#!/usr/bin/env bash
set -euo pipefail

version="-dev"
if [[ "$FORGEJO_REF_TYPE" == "tag" ]]; then
  version="-$FORGEJO_REF_NAME"
else
  version="-$FORGEJO_SHA"
fi

mkdir -p release
cd crates/gram
pycargoebuild -c --features --no-config --no-license --no-manifest --distdir ../../release --crate-tarball-path "../../gram${version}-crates.tar.xz" .
cd ../..

# check. remove if ok
cp "gram${version}-crates.tar.xz" "release/gram${version}-crates.tar.xz"

echo "name=gram${version}-crates.tar.xz" >> "$FORGEJO_OUTPUT"
