# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
name: CI

on:
  push:
    branches:
      - main
      - test/*
      - test-gh/*
    tags:
      - "*"

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: "1"
  CARGO_INCREMENTAL: "0"

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a # v7.0.1
        with:
          fetch-depth: 0

      - name: Fix Microslop # https://github.com/microsoft/python-environment-tools/issues/171
        if: runner.os == 'Windows'
        run: git config --global core.longpaths true

      - name: Update cargo path
        if: runner.os == 'macOS'
        run: echo "/Users/runner/.cargo/bin" >> $GITHUB_PATH

      - uses: taiki-e/install-action@b6b84cf49ebfe0176417bdce007c624f0db37f20 # v2.86.2
        with:
          tool: cargo-nextest

      - name: Cache Rust build
        uses: Swatinem/rust-cache@f0d9c3887740aee45f6153b24b3a6b815192ec16 # v2.9.3

      - name: Install dependencies
        if: runner.os == 'Linux'
        run: ./script/prepare-ci ci

      - name: Run nextest
        if: runner.os == 'Windows'
        env:
          MAKEOPTS: "-j2 -l2"
          CARGO_BUILD_JOBS: "2"
        run: cargo nextest run --workspace --no-fail-fast --success-output never --show-progress none

      - name: Run nextest
        if: runner.os != 'Windows'
        run: cargo nextest run --workspace --no-fail-fast --success-output never --show-progress none

  build-linux:
    name: Build Linux (${{ matrix.arch }})
    if:
      github.ref_type == 'tag' || startsWith(github.ref, 'refs/heads/test/') || startsWith(github.ref,
      'refs/heads/test-gh/')
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - arch: x86_64
            runner: ubuntu-latest # v24.04
            artifact_name: linux-x86_64
          - arch: aarch64
            runner: ubuntu-24.04-arm
            artifact_name: linux-aarch64
    env:
      CC: clang
      CXX: clang++
      CC_x86_64_unknown_linux_musl: musl-gcc
      CC_aarch64_unknown_linux_musl: musl-gcc
    steps:
      - uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a # v7.0.1
        with:
          fetch-depth: 0

      - name: Cache Rust build
        uses: Swatinem/rust-cache@f0d9c3887740aee45f6153b24b3a6b815192ec16 # v2.9.3

      - name: Install dependencies
        run: ./script/prepare-ci release

      - name: Flatpak dependencies
        run: ./script/flatpak/deps

      - name: Bundle Flatpak
        run: ./script/flatpak/bundle-flatpak

      - name: Copy artifacts
        shell: bash
        run: |
          find target -name '*.gz'
          version="-dev"
          if [[ "$GITHUB_REF_TYPE" == "tag" ]]; then
            version="-$GITHUB_REF_NAME"
          else
            version="-$GITHUB_SHA"
          fi
          mkdir artifacts
          cp "target/release/gram-linux-${{ matrix.arch }}.tar.gz" "artifacts/gram-linux-${{ matrix.arch }}${version}.tar.gz"
          cp "target/gram-remote-server-linux-${{ matrix.arch }}.gz" "artifacts/gram-remote-server-linux-${{ matrix.arch }}${version}.gz"
          cp "target/release/app.liten.Gram.flatpak" "artifacts/app.liten.Gram-${{ matrix.arch }}${version}.flatpak"

      - name: Upload artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ matrix.artifact_name }}
          path: artifacts/*

  build-windows:
    name: Build Windows
    if:
      github.ref_type == 'tag' || startsWith(github.ref, 'refs/heads/test/') || startsWith(github.ref,
      'refs/heads/test-gh/')
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - build: windows
            os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: windows-x64
    steps:
      - uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a # v7.0.1

      - name: Fix Microslop # https://github.com/microsoft/python-environment-tools/issues/171
        run: git config --global core.longpaths true

      - name: Cache Rust build
        uses: Swatinem/rust-cache@f0d9c3887740aee45f6153b24b3a6b815192ec16 # v2.9.3

      - name: Bundle Windows
        run: script/bundle-windows.ps1 -Architecture x86_64
        shell: pwsh

      - name: List
        shell: bash
        run: |
          ls -la target/*

      - name: Upload Gram
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: Gram-${{ matrix.artifact_name }}-${{ matrix.target }}.exe
          path: target/Gram-x86_64.exe
          if-no-files-found: error

      - name: Upload remote-server
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: gram-remote-server-${{ matrix.artifact_name}}-${{ matrix.target }}.zip
          path: target/gram-remote-server-windows-x86_64.zip
          if-no-files-found: warn
